;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/network-wifi]
type = custom/script

; Command to execute - Update path to where you place network-wifi.sh
exec = ~/YourPath/scripts/network-wifi.sh
interval = 1
tail = true

format = <label>
format-foreground = ${color.foreground}

; Click to open WiFi menu - Update path to your wifimenu.sh wrapper script
label = "%{A1:~/YourPath/scripts/wifimenu.sh &:}%output%%{A}"
click-left = ~/YourPath/scripts/wifimenu.sh

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_